name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6.2.0
      - uses: denoland/setup-deno@909c0c441fb18c26536c4a0e2ca7836e96e42e4c # v2.2.0
        with:
          deno-version: v2.7.1
      - run: deno task check
      - run: deno task test:all
      - name: Check not a dev version
        run: |
          VERSION=$(deno eval "import denoJson from './deno.json' with { type: 'json' }; console.log(denoJson.version)")
          if echo "$VERSION" | grep -q "\-dev"; then
            echo "Error: version '$VERSION' contains '-dev'. Aborting publish."
            exit 1
          fi
          echo "Version: $VERSION (OK)"
      - name: Dry run publish
        run: deno publish --dry-run
      - name: Publish package
        run: deno publish
